### PR TITLE
feat: allow queueName to be given as option

### PR DESCRIPTION
**Pull request by tanguyantoine**
# Description

Add a `queueName` option to the consumer constructor 

# Why

It let consumer be started on the fly.

One use case would be to start consumers from a main consumer.

ex: 

```ts

class MainConsumer extends Consumer {
 static queueName = 'main'

  consume(message, cb) {
    new GenericConsumer(config, { queueName: message}).run()
    cb()
  }
}

class GenericConsumer extends Consumer {
  consume(message, cb) {}
}
```

**NB**: happy to get help to implement tests :-)

### CODE REVIEW

**Comment by numidiasoft** [comment]
+1

**Comment by weyoss** [comment]
@tanguyantoine Thank you for trying to make this project better.

Right now I am bit busy, but I am considering your PR.

I will keep you updated.

**Comment by tanguyantoine** [comment]
up

**Comment by weyoss** [comment]
Your suggestion has been accepted. Please upgrade your  RedisSMQ installation.

**Comment by weyoss** [comment]
Closing this PR as outdated

**Pull request closed without merging**
